.TH gcs_skel 1 "July 16, 2010" "Guadalinex Configuration System"
.SH NAME
gcs_skel \- generate a GCS skeleton
.SH SYNOPSIS
.B gcs_skel
.SH DESCRIPTION
.PP
Generate a skeleton of directories to configure and build with gcs_build
.SH SEE ALSO
.BR gcs_build (1).
.br
.SH AUTHOR
Junta de Andalucia <packmaster@guadalinex.org>
.PP
This manual page was written by Enrique Hernández Bello <quique@osl.ull.es>,
for the Debian project and may be used by others.
