.TH gcs_build 1 "July 16, 2010" "Guadalinex Configuration System"
.SH NAME
gcs_build \- build a Debian package
.SH SYNOPSIS
.B gcs_build
.RI [ -S ]
.SH DESCRIPTION
.PP
Build a package from a customized skeleton spawned by gcs_skel
.SH OPTIONS
.B \-h, \-\-help
Show summary of options.
.TP
.B \-S, \-\-sources
debian source only, don't build binary files
.SH SEE ALSO
.BR gcs_skel (1).
.br
.SH AUTHOR
Junta de Andalucia <packmaster@guadalinex.org>
.PP
This manual page was written by Enrique Hernández Bello <quique@osl.ull.es>,
for the Debian project and may be used by others.
